/**
 */
package IFML.Mobile.provider;

import IFML.Mobile.util.MobileAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class MobileItemProviderAdapterFactory extends MobileAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MobileItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.Screen} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScreenItemProvider screenItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.Screen}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScreenAdapter() {
		if (screenItemProvider == null) {
			screenItemProvider = new ScreenItemProvider(this);
		}

		return screenItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.ToolBar} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToolBarItemProvider toolBarItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.ToolBar}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToolBarAdapter() {
		if (toolBarItemProvider == null) {
			toolBarItemProvider = new ToolBarItemProvider(this);
		}

		return toolBarItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.MobileComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MobileComponentItemProvider mobileComponentItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.MobileComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMobileComponentAdapter() {
		if (mobileComponentItemProvider == null) {
			mobileComponentItemProvider = new MobileComponentItemProvider(this);
		}

		return mobileComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.MobileElementEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MobileElementEventItemProvider mobileElementEventItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.MobileElementEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMobileElementEventAdapter() {
		if (mobileElementEventItemProvider == null) {
			mobileElementEventItemProvider = new MobileElementEventItemProvider(this);
		}

		return mobileElementEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.MobileSystemEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MobileSystemEventItemProvider mobileSystemEventItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.MobileSystemEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMobileSystemEventAdapter() {
		if (mobileSystemEventItemProvider == null) {
			mobileSystemEventItemProvider = new MobileSystemEventItemProvider(this);
		}

		return mobileSystemEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.BatteryEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BatteryEventItemProvider batteryEventItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.BatteryEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBatteryEventAdapter() {
		if (batteryEventItemProvider == null) {
			batteryEventItemProvider = new BatteryEventItemProvider(this);
		}

		return batteryEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.StorageEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StorageEventItemProvider storageEventItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.StorageEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStorageEventAdapter() {
		if (storageEventItemProvider == null) {
			storageEventItemProvider = new StorageEventItemProvider(this);
		}

		return storageEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.MobileAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MobileActionItemProvider mobileActionItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.MobileAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMobileActionAdapter() {
		if (mobileActionItemProvider == null) {
			mobileActionItemProvider = new MobileActionItemProvider(this);
		}

		return mobileActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.CameraAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CameraActionItemProvider cameraActionItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.CameraAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCameraActionAdapter() {
		if (cameraActionItemProvider == null) {
			cameraActionItemProvider = new CameraActionItemProvider(this);
		}

		return cameraActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.MicrophoneAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MicrophoneActionItemProvider microphoneActionItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.MicrophoneAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMicrophoneActionAdapter() {
		if (microphoneActionItemProvider == null) {
			microphoneActionItemProvider = new MicrophoneActionItemProvider(this);
		}

		return microphoneActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.MobileActionEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MobileActionEventItemProvider mobileActionEventItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.MobileActionEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMobileActionEventAdapter() {
		if (mobileActionEventItemProvider == null) {
			mobileActionEventItemProvider = new MobileActionEventItemProvider(this);
		}

		return mobileActionEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.CameraActionEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CameraActionEventItemProvider cameraActionEventItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.CameraActionEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCameraActionEventAdapter() {
		if (cameraActionEventItemProvider == null) {
			cameraActionEventItemProvider = new CameraActionEventItemProvider(this);
		}

		return cameraActionEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link IFML.Mobile.MicrophoneActionEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MicrophoneActionEventItemProvider microphoneActionEventItemProvider;

	/**
	 * This creates an adapter for a {@link IFML.Mobile.MicrophoneActionEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMicrophoneActionEventAdapter() {
		if (microphoneActionEventItemProvider == null) {
			microphoneActionEventItemProvider = new MicrophoneActionEventItemProvider(this);
		}

		return microphoneActionEventItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (screenItemProvider != null) screenItemProvider.dispose();
		if (toolBarItemProvider != null) toolBarItemProvider.dispose();
		if (mobileComponentItemProvider != null) mobileComponentItemProvider.dispose();
		if (mobileElementEventItemProvider != null) mobileElementEventItemProvider.dispose();
		if (mobileSystemEventItemProvider != null) mobileSystemEventItemProvider.dispose();
		if (batteryEventItemProvider != null) batteryEventItemProvider.dispose();
		if (storageEventItemProvider != null) storageEventItemProvider.dispose();
		if (mobileActionItemProvider != null) mobileActionItemProvider.dispose();
		if (cameraActionItemProvider != null) cameraActionItemProvider.dispose();
		if (microphoneActionItemProvider != null) microphoneActionItemProvider.dispose();
		if (mobileActionEventItemProvider != null) mobileActionEventItemProvider.dispose();
		if (cameraActionEventItemProvider != null) cameraActionEventItemProvider.dispose();
		if (microphoneActionEventItemProvider != null) microphoneActionEventItemProvider.dispose();
	}

}
